### PR TITLE
Add support for Secret Network v1.2.2

### PR DESCRIPTION
**Pull request by fjij**
Add support for [Secret Network v1.2.2](https://github.com/scrtlabs/SecretNetwork) so you can run Secret Network nodes on Akash.

Refer to the [docs for reference](https://build.scrt.network/validators-and-full-nodes/run-full-node-mainnet.html#run-a-full-node).

Please let me know if there are any important changes to be made, new to setting up Akash containers.

### CODE REVIEW

**Comment by betterclever** [comment]
@fjij Did you test out the compose file locally? The `make install` command will most likely fail since the secret network uses a different installation format.

**Comment by fjij** [comment]
> @fjij Did you test out the compose file locally? The `make install` command will most likely fail since the secret network uses a different installation format.

Thanks for pointing this out. I changed the make target, but this would obviously not work for the other images. Is there a way to add additional run steps into the base Dockerfile for specific images? Because I also noticed that the Secret Network node needs to run a script before make can be run.

**Comment by betterclever** [comment]
I think adaptability has to be considered to support Secretnetwork as we tried to do with other chains. Just look at the history of the current Dockerfile, that will try to give you an idea about how we have tried to make it modular over the time.

**Comment by fjij** [comment]
I'll spend a little more time looking at the best way to do this and I'll make a new PR when I'm done

**Comment by tombeynon** [comment]
@fjij thanks for this - take a look at how `juno` and `cheqd` (starport) work - both have more custom installation branches in the Dockerfile that can be run before/after/instead of the `make install` step.

**Pull request closed without merging**
