### PR TITLE
Replace some ARG with ENV to avoid invalidation in later builds.

### PR DESCRIPTION
**Pull request by Glacier-Luo**

### CODE REVIEW

**Comment by tombeynon** [comment]
These should be ARG not ENV variables, could you explain this change a bit more?

**Comment by Glacier-Luo** [comment]
``` bash
➜  cosmos-omnibus git:(master) ✗ docker build . --build-arg "http_proxy=http://127.0.0.1:7890" --build-arg "https_proxy=http://127.0.0.1:7890" --network host -t temp
Sending build context to Docker daemon  482.8kB
Step 1/59 : ARG BUILD_IMAGE=default
Step 2/59 : ARG BUILD_METHOD=source
Step 3/59 : ARG GOLANG_VERSION=1.16-buster
Step 4/59 : FROM golang:${GOLANG_VERSION} AS build_base
 ---> 5957ecd0d41f
Step 5/59 : ARG PROJECT=akash
 ---> Using cache
 ---> 9bf3243cbf3e
Step 6/59 : ARG PROJECT_BIN=$PROJECT
 ---> Using cache
 ---> 32b44c96049e
Step 7/59 : ARG APT_INSTALL_EXTRA_DEPS
 ---> Using cache
 ---> 6418d6905902
Step 8/59 : RUN apt-get update &&   apt-get install --no-install-recommends --assume-yes curl unzip ${APT_INSTALL_EXTRA_DEPS} &&   apt-get clean
 ---> Using cache
 ---> 791cafc7a31d
Step 9/59 : FROM build_base AS build_source
 ---> 791cafc7a31d
Step 10/59 : ARG VERSION=v0.12.1
 ---> Using cache
 ---> 2974559104c1
Step 11/59 : ARG REPOSITORY=https://github.com/ovrclk/akash.git
 ---> Using cache
 ---> 9e3009e40c79
Step 12/59 : ARG BUILD_COMMAND="make install"
 ---> Using cache
 ---> 6fa5fea9e2d7
Step 13/59 : RUN git clone $REPOSITORY /data
 ---> Using cache
 ---> 5e252e14fc03
Step 14/59 : WORKDIR /data
 ---> Using cache
 ---> 8f07c33221aa
Step 15/59 : RUN git checkout $VERSION
 ---> Using cache
 ---> 14ec00b30375
Step 16/59 : FROM build_source AS build_starport
 ---> 14ec00b30375
Step 17/59 : ARG BUILD_COMMAND="starport chain build"
 ---> Using cache
 ---> 96dfdf709918
Step 18/59 : RUN curl https://get.starport.network/starport! | bash
 ---> Using cache
 ---> d3ed7f97dae8
Step 19/59 : FROM build_${BUILD_METHOD} AS build
 ---> 14ec00b30375
Step 20/59 : RUN $BUILD_COMMAND
 ---> Running in 5c9c8565203f
Removing intermediate container 5c9c8565203f
 ---> c3ea578b1b96
Step 21/59 : RUN ldd $GOPATH/bin/$PROJECT_BIN | tr -s '[:blank:]' '\n' | grep '^/' |     xargs -I % sh -c 'mkdir -p $(dirname deps%); cp % deps%;'
 ---> Running in ded004dab326
ldd: /go/bin/: not regular file
Removing intermediate container ded004dab326
 ---> 49b33b2391b5
Step 22/59 : RUN mv $GOPATH/bin/$PROJECT_BIN /bin/$PROJECT_BIN
 ---> Running in bc7ce9aa2a70
Removing intermediate container bc7ce9aa2a70
 ---> 435e085c664d
Step 23/59 : FROM debian:buster AS default
 ---> 6642e362a825
Step 24/59 : ARG PROJECT=akash
 ---> Using cache
 ---> aeb0e7f06173
Step 25/59 : ARG PROJECT_BIN=$PROJECT
 ---> Using cache
 ---> 25774de69fe3
Step 26/59 : COPY --from=build /bin/$PROJECT_BIN /bin/$PROJECT_BIN
COPY failed: stat bin/akash: file does not exist
```

The important thing is here.
``` bash
 ---> 14ec00b30375
Step 20/59 : RUN $BUILD_COMMAND
 ---> Running in 5c9c8565203f
Removing intermediate container 5c9c8565203f
 ---> c3ea578b1b96
Step 21/59 : RUN ldd $GOPATH/bin/$PROJECT_BIN | tr -s '[:blank:]' '\n' | grep '^/' |     xargs -I % sh -c 'mkdir -p $(dirname deps%); cp % deps%;'
 ---> Running in ded004dab326
ldd: /go/bin/: not regular file
```
In step 20, it did nothing, becasue of the `$BUILD_CCOMMAND` doesn't exist.
And in step 21, The variable `$PROJECT_BIN` does not exist.So it says `/go/bin/:not regular file`.

**Comment by tombeynon** [comment]
The build process requires `buildx` which is why it's not building correctly in your example. See the `.github/workflows/publish.yml` file which actually builds the images.

You also shouldn't need to build these yourself unless you plan on contributing a new chain

**Comment by Glacier-Luo** [comment]
Ok，i know that.
I want to build by my self because i want to know why it always exits.

**Comment by tombeynon** [comment]
If you use `docker buildx build` instead of `docker build` it will use `buildx` correctly, but I'd be surprised if the issues you are having are a problem with the container image. I've enabled tests on this PR so you can see if the changes you're making work or not.

**Pull request closed without merging**
