### PR TITLE
Update Akash to v0.16.3

### PR DESCRIPTION
**Pull request by tombeynon**

### CODE REVIEW

**Comment by tombeynon** [comment]
I so nearly did but decided to play it safe 😂

**Comment by arno01** [comment]
- `0.16.3` is the actual version now.

**Comment by arno01** [comment]
If anyone wants to use it right now, I've just build it off of this PR.
And pushed 0.16.3 to `andrey01/cosmos-omnibus:v0.0.31-akash-v0.16.3` (on docker hub)
Or you can build & push your own image following my steps:

```
arno@stealth:~/git/cosmos-omnibus$ git fetch origin pull/170/head:pr170
From https://github.com/ovrclk/cosmos-omnibus
 * [new ref]         refs/pull/170/head -> pr170
 * 
arno@stealth:~/git/cosmos-omnibus$ git checkout pr170
Switched to branch 'pr170'

arno@stealth:~/git/cosmos-omnibus$ cd akash/
arno@stealth:~/git/cosmos-omnibus/akash$ touch ../.env
arno@stealth:~/git/cosmos-omnibus/akash$ docker buildx bake -f build.yml --set node_1.tags=andrey01/cosmos-omnibus:v0.0.31-akash-v0.16.3
[+] Building 214.0s (22/22) FINISHED                                                                                                         
 => [internal] load build definition from Dockerfile                                                                                    1.2s
 => => transferring dockerfile: 2.91kB                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                       0.9s
 => => transferring context: 2B                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/debian:buster                                                                        0.0s
 => [internal] load metadata for docker.io/library/golang:1.17-buster                                                                   3.1s
 => [auth] library/golang:pull token for registry-1.docker.io                                                                           0.0s
 => [build_base 1/2] FROM docker.io/library/golang:1.17-buster@sha256:74ba26bff6b9335172e4a84c6bb69a6fd3876c9d06ce7839ff7cc14637893f9  43.6s
 => => resolve docker.io/library/golang:1.17-buster@sha256:74ba26bff6b9335172e4a84c6bb69a6fd3876c9d06ce7839ff7cc14637893f9d             0.3s
 => => sha256:74ba26bff6b9335172e4a84c6bb69a6fd3876c9d06ce7839ff7cc14637893f9d 1.86kB / 1.86kB                                          0.0s
 => => sha256:af6de82006b8c1296ec539f3cb628956006d0df6ac6b93cb484c1c030a148257 1.79kB / 1.79kB                                          0.0s
 => => sha256:bf6c4a9906628954a0a606132a7ad529f8a6ab8948d0ce52eca96ab925702a95 7.04kB / 7.04kB                                          0.0s
 => => sha256:85bed84afb9a834cf090b55d2e584abd55b4792d93b750db896f486680638344 50.44MB / 50.44MB                                       15.0s
 => => sha256:5fdd409f4b2bf3771fac1cbc2df46d1cbb4b800b154cfc33e8e0cd23e67ab3e0 7.86MB / 7.86MB                                          3.1s
 => => sha256:fa3069e6cecf9d5e43ace0a925b53849b2fd189ef41883d45d8f2e12213c2c06 10.00MB / 10.00MB                                        3.4s
 => => sha256:21b2aacb9bcb4d68740f7db755d0f604b9fef7abff0ce0f0fd759266d43c6002 68.80MB / 68.80MB                                       19.8s
 => => sha256:4ee16f45eff97cbe98b74c63ca2375b2c6b2592cd765a86df098f731baab13ad 51.84MB / 51.84MB                                       18.1s
 => => sha256:97c4483c13729a00222fd89aa00b2b6d765479fbf5990b1648ade5a2eeacb921 134.95MB / 134.95MB                                     32.8s
 => => extracting sha256:85bed84afb9a834cf090b55d2e584abd55b4792d93b750db896f486680638344                                               0.8s
 => => extracting sha256:5fdd409f4b2bf3771fac1cbc2df46d1cbb4b800b154cfc33e8e0cd23e67ab3e0                                               0.1s
 => => extracting sha256:fa3069e6cecf9d5e43ace0a925b53849b2fd189ef41883d45d8f2e12213c2c06                                               0.1s
 => => extracting sha256:4ee16f45eff97cbe98b74c63ca2375b2c6b2592cd765a86df098f731baab13ad                                               1.1s
 => => sha256:9ba06393f25d05d045c64abc384e8285a0940007ae3580674f1ee5e4d6ef4e5f 156B / 156B                                             19.9s
 => => extracting sha256:21b2aacb9bcb4d68740f7db755d0f604b9fef7abff0ce0f0fd759266d43c6002                                               1.6s
 => => extracting sha256:97c4483c13729a00222fd89aa00b2b6d765479fbf5990b1648ade5a2eeacb921                                               2.1s
 => => extracting sha256:9ba06393f25d05d045c64abc384e8285a0940007ae3580674f1ee5e4d6ef4e5f                                               0.0s
 => [internal] load build context                                                                                                       0.8s
 => => transferring context: 10.87kB                                                                                                    0.0s
 => [default 1/3] FROM docker.io/library/debian:buster                                                                                  0.6s
 => [build_base 2/2] RUN apt-get update &&   apt-get install --no-install-recommends --assume-yes curl unzip ${INSTALL_PACKAGES} &&     9.9s
 => [build_source 1/3] RUN git clone https://github.com/ovrclk/akash /data                                                             14.8s
 => [build_source 2/3] WORKDIR /data                                                                                                    0.7s 
 => [build_source 3/3] RUN git checkout v0.16.3                                                                                         1.3s 
 => [build 1/3] RUN make install                                                                                                       56.6s 
 => [build 2/3] RUN ldd /go/bin/akash | tr -s '[:blank:]' '\n' | grep '^/' |     xargs -I % sh -c 'mkdir -p $(dirname deps%); cp % dep  1.2s
 => [build 3/3] RUN mv /go/bin/akash /bin/akash                                                                                         2.8s
 => [default 2/3] COPY --from=build /bin/akash /bin/akash                                                                               1.3s
 => [default 3/3] COPY --from=build /data/deps/ /                                                                                       0.8s
 => [omnibus 1/4] RUN apt-get update &&   apt-get install --no-install-recommends --assume-yes ca-certificates curl wget file unzip g  59.7s
 => [omnibus 2/4] RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"   && unzip awscliv2.zip -d /us  9.9s
 => [omnibus 3/4] COPY run.sh snapshot.sh /usr/bin/                                                                                     0.8s
 => [omnibus 4/4] RUN chmod +x /usr/bin/run.sh /usr/bin/snapshot.sh                                                                     2.3s
 => exporting to image                                                                                                                  2.9s
 => => exporting layers                                                                                                                 2.8s
 => => writing image sha256:056ceca0479b608833815595b398e1da37b52321e6faf784fa4604fb2fc7fbdf                                            0.1s
 => => naming to docker.io/andrey01/cosmos-omnibus:v0.0.31-akash-v0.16.3                                                                0.0s
arno@stealth:~/git/cosmos-omnibus/akash$ echo $?
0

arno@stealth:~/git/cosmos-omnibus/akash$ docker push andrey01/cosmos-omnibus:v0.0.31-akash-v0.16.3
The push refers to repository [docker.io/andrey01/cosmos-omnibus]
6d1bcbae7344: Pushed 
3f66933581b1: Pushed 
7a39c40150c1: Pushed 
29623adc3a34: Pushed 
5055c52a0ba8: Pushed 
cc5f54578ae8: Pushed 
d6a325d281f2: Mounted from andrey01/pkt_on_akash 
v0.0.31-akash-v0.16.3: digest: sha256:2a45c83ae53927e553ecb3ef8b307a83c34e8536d849420f5bebee8a4344f8b5 size: 1791
```

**Comment by tombeynon** [comment]
Thanks @arno01, just releasing a new version now

**Pull request merged**
